TaskManager/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TaskManager;

namespace TaskManager.Controllers
{
    [Auth.Auth("Admin")]
    public class DocumentController : Controller
    {
        private TaskManagerDbEntities db = new TaskManagerDbEntities();

      
        public ActionResult Index()
        {
          
            return View();
        }

        //veri tabanından gelen veri listesini tabloya döker
        public ActionResult MyChart()
        {
            var task = db.Sp_ListTask().ToList();
          
            var testChart = new Chart(width: 600, height: 400)
            .AddTitle("Test")
            .DataBindTable(dataSource: task, xField: "Score")
            .GetBytes("png");
            return File(testChart, "image/png");

        }

      
   
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaskManager/Controllers/ProjectController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace TaskManager.Controllers
{

    [Auth.Auth("Admin")]
    public class ProjectController : Controller
    {
        private TaskManagerDbEntities db = new TaskManagerDbEntities();


        /*Arama textboxında kelimeyi otomatik tamamlaması için*/
        [HttpPost]
        public ActionResult Autocomplete(string key)
        {

            var sonuc = (from r in db.Project
                         where r.ProjectName.ToLower().Contains(key.ToLower())
                         select new { r.ProjectName }).Distinct();
          
            return this.Json(sonuc,
                       JsonRequestBehavior.AllowGet);/*json tipinde döner*/

        }
  
        //Projelerin tamamını listeler. id ve name admin idsi ve ismidir.
        public ActionResult Index(Guid? id)
        {
            var project = db.Project.Include(p => p.TAdmin);
            ViewBag.ManagerID = id;
            return View(project.ToList());
        }

       //Post işlemleri için. Arama yapmak için entera basarsa veri tabanında o projeyi aratıp sonucu döner
        [HttpPost]
        public ActionResult Index(string Search,Guid id)
        {

            var sonuc = db.Project.Where(m => m.ProjectName.Contains(Search)).ToList();
            ViewBag.ManagerID = id;
            return View(sonuc);


        }
     
        //proje oluştur get işlemleri
        public ActionResult Create(Guid ManagerId)
        {
            var result = db.TAdmin.Find(ManagerId);
            ViewBag.ManagerId =ManagerId;
            ViewBag.ManagerName = result.Username;
          
            return View();
        }

        //proje oluşturulur managerid ve managername adminin başka admin adına proje oluşturmaması içindir. 
        //Admin sadece kendi adıyla proje oluşturabilir.
         [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectName,ProjectKey,ProjectManager,ProjectID")] Project project,Guid managerid,string managername)
        {
            project.ProjectManager = managerid;
            if (ModelState.IsValid)
            {
                db.Project.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index",new { id = managerid, name = managername });
            }

            ViewBag.ProjectManager = new SelectList(db.TAdmin, "ManagerID", "Username", project.ProjectManager);
            return View(project);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="@Url.Content("~/Content/tm.png")" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
  
  

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
               
            
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
              
                    <li><a href="#" rel="stylesheet" type="text/css">Task Manager</a></li> 
                    <li>@Html.ActionLink("Raporlar", "Index", "Document")</li>
                    <li>@Html.ActionLink("Projeler", "Index", "Project",new { id = @Session["ID"] },null)</li>
                    <li>@Html.ActionLink("Proje Oluştur", "Create", "Project", new { ManagerId = @Session["ID"] }, null)</li>
                    <li>@Html.ActionLink("Görevler", "GetTask", "Task",new { userid = @Session["ID"] },null)</li>
                    <li>@Html.ActionLink("Görev Oluştur", "CreateTask", "Task",new { id = @Session["ID"],name = Session["ManagerName"] },null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
      
        <hr/>
        @RenderBody()
     
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</body>
</html>